/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package percabangan;

/**
 *
 * @author lenovo
 */
public class aplikasiHitungGaji extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(aplikasiHitungGaji.class.getName());

    /**
     * Creates new form aplikasiHitungGaji
     */
    public aplikasiHitungGaji() {
        initComponents();
        reset(); //Memanggil Method Reset
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tNamaKaryawan = new javax.swing.JTextField();
        tJumlahHariKerja = new javax.swing.JTextField();
        tJabatan = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jNamaKaryawan = new javax.swing.JLabel();
        jJumlahHariKerja = new javax.swing.JLabel();
        jPerhitunganGaji = new javax.swing.JLabel();
        jTotalGaji = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Hitung Gaji");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Karyawan"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jLabel2.setText("Nama Karyawan");

        jLabel3.setText("Jumlah Hari Kerja");

        jLabel4.setText("Jabatan");

        tNamaKaryawan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNamaKaryawanKeyReleased(evt);
            }
        });

        tJumlahHariKerja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tJumlahHariKerjaKeyReleased(evt);
            }
        });

        tJabatan.setBackground(new java.awt.Color(255, 255, 255));
        tJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Supervisor", "Staff" }));
        tJabatan.addActionListener(this::tJabatanActionPerformed);
        tJabatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tJabatanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tJabatanKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addComponent(tNamaKaryawan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tJumlahHariKerja)
                            .addComponent(tJabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tJumlahHariKerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tJabatan))
                .addContainerGap())
        );

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/percabangan/icon/icons8-reset-15.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnHitung.setBackground(new java.awt.Color(255, 255, 255));
        btnHitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/percabangan/icon/icons8-calculator-15.png"))); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);
        btnHitung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnHitungKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel2KeyReleased(evt);
            }
        });

        jNamaKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNamaKaryawan.setText("jLabel9");

        jJumlahHariKerja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jJumlahHariKerja.setText("jLabel10");

        jPerhitunganGaji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPerhitunganGaji.setText("jLabel11");

        jTotalGaji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotalGaji.setText("jLabel12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNamaKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jJumlahHariKerja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPerhitunganGaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTotalGaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNamaKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jJumlahHariKerja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPerhitunganGaji)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTotalGaji)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnTutup.setBackground(new java.awt.Color(255, 255, 255));
        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/percabangan/icon/icons8-close-15 (3).png"))); // NOI18N
        btnTutup.setText("Tutup");
        btnTutup.addActionListener(this::btnTutupActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHitung)
                                .addGap(6, 6, 6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTutup)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnHitung))
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTutup)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:re
        reset(); //Memanggil Method Reset
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        hitung(); //Memanggil Method Hitung
        
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        System.exit(0); //Untuk Menutup Aplikasi
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnHitungKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHitungKeyReleased
        // TODO add your handling code here:
        hitung(); //Memanggil Method Hitung
    }//GEN-LAST:event_btnHitungKeyReleased

    private void tNamaKaryawanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNamaKaryawanKeyReleased
        // TODO add your handling code here:
         //Deklarasi
         String namaKaryawan = tNamaKaryawan.getText();
         //Output
        jNamaKaryawan.setText("Nama Pelanggan : "+namaKaryawan);
    }//GEN-LAST:event_tNamaKaryawanKeyReleased

    private void tJumlahHariKerjaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tJumlahHariKerjaKeyReleased
        // TODO add your handling code here:
        hitung();
       
    }//GEN-LAST:event_tJumlahHariKerjaKeyReleased

    private void tJabatanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tJabatanKeyReleased
        // TODO add your handling code here:
        hitung();
 
    }//GEN-LAST:event_tJabatanKeyReleased

    private void jPanel2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jPanel2KeyReleased

    private void tJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJabatanActionPerformed
        // TODO add your handling code here:
        hitung();
        
    }//GEN-LAST:event_tJabatanActionPerformed

    private void tJabatanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tJabatanKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tJabatanKeyPressed

    /**
     * @param args the command line arguments
     */
    
    void reset(){
        tNamaKaryawan.setText(null);
        tJumlahHariKerja.setText(null);
        jJumlahHariKerja.setText(null);
        jNamaKaryawan.setText(null);
        jPerhitunganGaji.setText(null);
        jTotalGaji.setText(null);
    }
    
    void hitung(){
        //Deklarasi
        
        String namaKaryawan= tNamaKaryawan.getText();
        int jumlahHariKerja = Integer.parseInt(tJumlahHariKerja.getText());
        String jabatan = tJabatan.getSelectedItem().toString();
        int gaji = 0, totalGaji;
        
        
        //Proses Menentukan Gaji
        if(jabatan == "Manager"){
            gaji = 25000;
        }else if(jabatan == "Supervisor"){
            gaji = 175000;
    }else if(jabatan == "Staff"){
      gaji = 100000;  
    }
        
        //Proses Menghitung Total Gaji
        totalGaji = jumlahHariKerja * gaji;
        
        //Output
        jNamaKaryawan.setText("Nama Karyawan : "+namaKaryawan);
        jJumlahHariKerja.setText("Jabatan : "+jabatan);
        jPerhitunganGaji.setText("Perhitungan Gaji : "+jumlahHariKerja+" hari"+ " x "+" Rp"+gaji);
        jTotalGaji.setText("Total Gaji : "+"Rp"+totalGaji);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new aplikasiHitungGaji().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jJumlahHariKerja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jNamaKaryawan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPerhitunganGaji;
    private javax.swing.JLabel jTotalGaji;
    private javax.swing.JComboBox<String> tJabatan;
    private javax.swing.JTextField tJumlahHariKerja;
    private javax.swing.JTextField tNamaKaryawan;
    // End of variables declaration//GEN-END:variables
}
